version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: project_t
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  php:
    container_name: php
    build:
      context: ./docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - '9000:9000'
    volumes:
      - ./app/:/var/www/app
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres